### PR TITLE
QPID-8516 Fix use of python2 in CMakeFiles excerpts

### PR DESCRIPTION
**Pull request by chrisrichardson77**

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]
I am uncertain about what we're trying to achieve there. For example, the Python binding library will need a lot more work to make it usable with Python 3... Are you simply trying to make the compilation work, with the intention of using the C++ parts?

I was wanting to compile the C++ client before, and I succeeded by configuring the project so that it does not build anything else. My build config is the following. It gets transformed into `cmake -D` options https://github.com/rh-messaging/cli-cpp/blob/master/BUILD.bazel#L62-L80

LGTM, I guess there is no harm in adding parens around `print` argument. It's a noop in Python 2.

**Comment by chrisrichardson77** [comment]
> I am uncertain about what we're trying to achieve there. For example, the Python binding library will need a lot more work to make it usable with Python 3... Are you simply trying to make the compilation work, with the intention of using the C++ parts?
> 
> I was wanting to compile the C++ client before, and I succeeded by configuring the project so that it does not build anything else. My build config is the following. It gets transformed into `cmake -D` options https://github.com/rh-messaging/cli-cpp/blob/master/BUILD.bazel#L62-L80
> 
> LGTM, I guess there is no harm in adding parens around `print` argument. It's a noop in Python 2.

Fair point about the python binding, I'm not sure what will happen after the configure phase but I was thinking that could be part of a larger piece of work.
The managementgen change seems to be key though, since you updated it to python3 in QPID-8413 so I'm assuming the intention is that it should build on a python3-only system.

**Comment by jiridanek** [comment]
> I'm assuming the intention is that it should build on a python3-only system.

OK, that's something I can get behind. We should have a CI for this...

**Comment by jiridanek** [comment]
LGTM, I guess we can merge it.

**Comment by jiridanek** [comment]
@chrisrichardson77 Do you have permissions to merge to qpid-cpp repository or do you need someone to do the merge for you?

**Comment by chrisrichardson77** [comment]
Merged - I guess I can! :)

**Comment by jiridanek** [comment]
Awsum; just for future reference, it makes IMO more sense to use one of the merge strategies without the merge commit, especially when the PR itself is just a single commit. Some people avoid the GitHub UI entirely, which I don't want to do, but I take care not to push in merge commits. 
image

**Comment by chrisrichardson77** [comment]
Will do, thanks for the tip!

**Pull request merged**
